### ISSUE TITLE
使用QQQ W4A8量化后的模型好像有问题。。。

### ISSUE THREAD

**Issue by Zhao-Dongyu** [HandH1998/QQQ#7]
您好 @HandH1998 ，我严格按照README提供的操作流程，对Llama2 7B chat模型执行了QQQ量化操作，使用的是quant_config/llama/w4a8-pergroup.yaml，修改了calibration_path，然后执行：
```bash
python3 examples/quant_model.py \
--model_path ${model_path} \
--tokenizer_path ${tokenizer_path} \
--batch_size 8 \
--dtype float16 \
--quant_config quant_config/llama/w4a8-pergroup.yaml
--save_path ${save_path}
```
得到量化模型，接着执行inference：
```bash
python3 examples/test_model.py \
--model_path ${quantized_model_path} \
--tokenizer_path ${tokenizer_path} \
--prompt "why do people need to sleep?" \
--max_new_tokens 128
```
得到的结果完全不合理：
<img width="1363" alt="截屏2024-07-26 上午10 57 31" src="https://github.com/user-attachments/assets/81963b16-ea1d-4bd2-921a-aee1402ffa80">
但使用原版Llama 7B chat模型推理能得到合理的结果：
![20240726002](https://github.com/user-attachments/assets/1aa4b917-36d1-49ec-97ab-d8edec1e2dfa)
请问这个问题是怎么产生的呢？QQQ量化算法是否有问题？

**Comment by HandH1998** [comment]
@Zhao-Dongyu Hello, I think the issue is relevant with the inference script `https://github.com/HandH1998/QQQ/blob/main/examples/test_model.py`, instead of the quantized model weights. Our inference script only supports simple text completion for `base model` like llama-2-7b-base. If you want to do the inference with `chat model` like llama-2-7b-chat, you should modify our script following the section `Intended Use` of [https://huggingface.co/meta-llama/Llama-2-7b-chat-hf](url).

**Comment by Zhao-Dongyu** [comment]
Thanks for your explanation :)
